name: multilingual_demo
description: Multilingual demo in Flutter
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: 0.17.0
  provider: 5.0.0
  flutter_secure_storage: 4.2.1

flutter:
  generate: true
  uses-material-design: true

flutter_intl:
  enabled: true
